name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: shantanu-bit
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push Snake Image
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Update Snake Animation"
          add: "./output/*"  # This will add all files from the output folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
